### ISSUE TITLE
One of the sources for assign has an enumerable key on the prototype chain

### ISSUE THREAD

**Issue by jamesone** [relay-tools/react-relay-network-layer#60]
I'm getting the following error when trying to use this package on `react-native (0.55.4)`:

```
ExceptionsManager.js:71 Unhandled JS Exception: One of the sources for assign has an enumerable key on the prototype chain. Are you trying to assign a prototype property? We don't allow it, as this is an edge case that we do not support. This error is a performance optimization and not spec compliant.
```

The simulator is throwing the following error:

![github screenshot 2018-06-05 17 49 09_preview](https://user-images.githubusercontent.com/1946920/40969224-2a2cd2c8-68d9-11e8-9e81-afede0072b1a.png)

You can see the simulator is referencing `fetchWithMiddleware.js (line: 41-13)`

Any ideas why this is happening? I've looked everywhere to try and find a solution, none of them work.

I believe it has something todo with a middleware I added, however, commenting this out doesn't fix the error:

```
let headers = {
x: 'y',
z: 'x',
};

...otherMiddlewares
next =>
        req => {
          Object.assign(req.headers, headers);
          return next(req);
        },
```

**Comment by nodkz** [comment]
Try to do it in such way:
```js
req.headers = Object.assign({}, req.headers, headers);
```

**Comment by jamesone** [comment]
After investigating this further, I found that removing `Object.assign` on line 7 in `fetchWithMiddleware` fixes the error.

```
var _extends = function (target) { for (var i = 1; i < arguments.length; i++) { var source = arguments[i]; for (var key in source) { if (Object.prototype.hasOwnProperty.call(source, key)) { target[key] = source[key]; } } } return target; };
```

I think this is an issue with react-native not allowing the use of Object.assign in certain scenarios.

**Comment by jamesone** [comment]
I had to add the following to `fetchWithMiddleware.js`: 

```
function extend(target) {
  for (var i = 1; i < arguments.length; i++) {
    var source = arguments[i];
    for (var key in source) {
      if (Object.prototype.hasOwnProperty.call(source, key)) {
        target[key] = source[key];
      }
    }
  }
  return target;
};
```

I then had to use it here:

`return extend({}, res, { payload: payload });` Inside the `runFetch` method
